language: go
go:
  - '1.15'
sudo: required
services:
  - docker
git:
  depth: false
matrix:
  include:
  - go: 1.15
arch:
  - amd64
  - ppc64le
before_script:
- mkdir -p bin
- export PATH=$PWD/bin:$PATH
script:
- make -k all test GOFLAGS_VENDOR=$( [ -d vendor ] && echo '-mod=vendor' )
  #after_success:
  #  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
  #      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" quay.io;
  #      make push GOFLAGS_VENDOR=$( [ -d vendor ] && echo '-mod=vendor' );
  #    fi
